repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      stages: [commit]
-   repo: local
    hooks:
    - id: isort
      name: Reorder python imports
      language: system
      entry: isort .
      always_run: true
      pass_filenames: false
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: pip freeze > requirements\requirements.txt;
               git add requirements\requirements.txt;
        language: system
        pass_filenames: false
        stages: [commit]
